/*
  # Signup Settings and Invitation System
  
  1. New Tables
    - `signup_settings`
      - Stores whether signup is public or private
      - Only one row should exist
    - `signup_invitations`
      - Stores invitation links generated by admins
      - Each invitation has a unique token
      - Can be used once or multiple times
      - Can be set to expire
      
  2. Security
    - Enable RLS on both tables
    - Only admins can manage settings
    - Anyone can read active invitations (to validate tokens)
*/

-- Create signup_settings table
CREATE TABLE IF NOT EXISTS signup_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  is_public boolean DEFAULT false,
  updated_at timestamptz DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id)
);

-- Insert default settings (signup is private by default)
INSERT INTO signup_settings (is_public)
SELECT false
WHERE NOT EXISTS (SELECT 1 FROM signup_settings);

-- Create signup_invitations table
CREATE TABLE IF NOT EXISTS signup_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text UNIQUE NOT NULL,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz,
  max_uses integer DEFAULT 1,
  current_uses integer DEFAULT 0,
  is_active boolean DEFAULT true
);

-- Enable RLS
ALTER TABLE signup_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE signup_invitations ENABLE ROW LEVEL SECURITY;

-- Policies for signup_settings (allow everyone to read, only admins can update)
CREATE POLICY "Anyone can read signup settings"
  ON signup_settings
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Admins can update signup settings"
  ON signup_settings
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin')
    )
  )
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin')
    )
  );

-- Policies for signup_invitations
CREATE POLICY "Anyone can read active invitations"
  ON signup_invitations
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true AND (expires_at IS NULL OR expires_at > now()));

CREATE POLICY "Admins can create invitations"
  ON signup_invitations
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin', 'manager')
    )
  );

CREATE POLICY "Admins can update invitations"
  ON signup_invitations
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin', 'manager')
    )
  )
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin', 'manager')
    )
  );

CREATE POLICY "Admins can delete invitations"
  ON signup_invitations
  FOR DELETE
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users
      WHERE raw_user_meta_data->>'role' IN ('super_admin', 'admin', 'manager')
    )
  );

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_signup_invitations_token ON signup_invitations(token);
CREATE INDEX IF NOT EXISTS idx_signup_invitations_active ON signup_invitations(is_active, expires_at) WHERE is_active = true;